#include "DaoProtocolServer.h"

#include <arpa/inet.h>
#include <chrono>
#include <cstdlib>
#include <iostream>
#include <sys/socket.h>
#include <thread>
#include <unistd.h>

using namespace dao::protocol;
static void require(bool ok,const char* what){if(!ok){std::cerr<<"FAIL: "<<what<<'\n';std::exit(1);}}
static int connectLocal(std::uint16_t port){sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(port);inet_pton(AF_INET,"127.0.0.1",&a.sin_addr);for(int i=0;i<50;++i){int fd=socket(AF_INET,SOCK_STREAM,0);if(fd>=0&&connect(fd,reinterpret_cast<sockaddr*>(&a),sizeof(a))==0)return fd;if(fd>=0)close(fd);std::this_thread::sleep_for(std::chrono::milliseconds(10));}return -1;}
static void sendFrame(int fd,MessageType type,std::uint32_t request,std::uint16_t version=1){Frame f;f.header.type=type;f.header.requestId=request;f.header.version=version;auto b=EncodeFrame(f);require(send(fd,b.data(),b.size(),0)==static_cast<ssize_t>(b.size()),"send request");}
int main()
{
    Header h;h.type=MessageType::LiveData;h.flags=0x10203040;h.payloadLength=99;h.sequenceNumber=7;h.requestId=42;std::array<std::uint8_t,kHeaderSize>b{};require(EncodeHeader(h,b),"header encode");Header d;require(DecodeHeader(b.data(),b.size(),d)&&d.flags==h.flags&&d.payloadLength==99&&d.requestId==42,"header decode/endian");
    Frame one;one.header.type=MessageType::Heartbeat;one.payload={1,2,3};auto bytes=EncodeFrame(one);StreamDecoder decoder;std::vector<Frame> frames;for(auto byte:bytes)require(decoder.Feed(&byte,1,frames)==StreamDecoder::Result::Ok,"split packet");require(frames.size()==1&&frames[0].payload==one.payload,"split reconstruction");frames.clear();std::vector<std::uint8_t> both=bytes;both.insert(both.end(),bytes.begin(),bytes.end());decoder.Reset();require(decoder.Feed(both.data(),both.size(),frames)==StreamDecoder::Result::Ok&&frames.size()==2,"multiple frames per recv");auto bad=b;bad[12]=0x7f;decoder.Reset();frames.clear();require(decoder.Feed(bad.data(),bad.size(),frames)==StreamDecoder::Result::Malformed,"invalid length reject");
    LiveData live;live.timestampUs=123;live.testId=9;live.forceN=100;live.rawDisplacementMm=2;live.complianceCompensationMm=.015;live.correctedDisplacementMm=1.985;live.extensometerMm=.5;live.testRunning=true;live.sampleFlags=7;LiveData round;require(DecodeLiveData(EncodeLiveData(live),round)&&round.rawDisplacementMm==2&&round.correctedDisplacementMm==1.985,"raw/corrected live roundtrip");TestDataChunk chunk{9,3,{1,4,9,16}};TestDataChunk chunkRound;require(DecodeTestDataChunk(EncodeTestDataChunk(chunk),chunkRound)&&chunkRound.bytes==chunk.bytes,"test data chunk roundtrip");
    constexpr std::uint16_t port=45551;ProtocolServer server(port);MachineStatus status{77,3,4,5,true};server.PublishStatus(status);server.PublishLiveData(live);server.SetCommandHandler([](MessageType t,const Frame&){return t==MessageType::StartTest?NackReason::MachineNotReady:NackReason::None;});require(server.Start(),"server start");std::uint8_t recvBuf[8192];int mismatch=connectLocal(port);require(mismatch>=0,"version test connect");sendFrame(mismatch,MessageType::Hello,9,2);const auto mismatchN=recv(mismatch,recvBuf,sizeof(recvBuf),0);StreamDecoder mismatchDecoder;std::vector<Frame> mismatchFrames;require(mismatchN>0&&mismatchDecoder.Feed(recvBuf,mismatchN,mismatchFrames)==StreamDecoder::Result::Ok&&!mismatchFrames.empty()&&mismatchFrames[0].header.type==MessageType::CommandNack,"HELLO version mismatch reject");close(mismatch);
    int fd=connectLocal(port);require(fd>=0,"connect");sendFrame(fd,MessageType::Hello,10);StreamDecoder network;std::vector<Frame> received;auto until=std::chrono::steady_clock::now()+std::chrono::milliseconds(450);while(std::chrono::steady_clock::now()<until){const auto n=recv(fd,recvBuf,sizeof(recvBuf),MSG_DONTWAIT);if(n>0)network.Feed(recvBuf,n,received);std::this_thread::sleep_for(std::chrono::milliseconds(5));}int liveCount=0;bool helloAck=false,statusSeen=false;for(const auto&f:received){helloAck|=f.header.type==MessageType::HelloAck;statusSeen|=f.header.type==MessageType::MachineStatus;liveCount+=f.header.type==MessageType::LiveData;}require(helloAck&&statusSeen&&liveCount>=3&&liveCount<=6,"HELLO/status/live 10Hz");sendFrame(fd,MessageType::StartTest,123);sendFrame(fd,MessageType::CommitRecipe,124);std::this_thread::sleep_for(std::chrono::milliseconds(30));received.clear();const auto n=recv(fd,recvBuf,sizeof(recvBuf),0);require(n>0&&network.Feed(recvBuf,n,received)==StreamDecoder::Result::Ok,"ACK/NACK receive");bool nackMatched=false,ackMatched=false;for(const auto&f:received){nackMatched|=f.header.type==MessageType::CommandNack&&f.header.requestId==123;ackMatched|=f.header.type==MessageType::CommandAck&&f.header.requestId==124;}require(nackMatched&&ackMatched,"ACK/NACK requestId matching");close(fd);
    int re=connectLocal(port);require(re>=0,"reconnect");sendFrame(re,MessageType::Hello,20);std::this_thread::sleep_for(std::chrono::milliseconds(30));received.clear();StreamDecoder resync;const auto rn=recv(re,recvBuf,sizeof(recvBuf),0);require(rn>0&&resync.Feed(recvBuf,rn,received)==StreamDecoder::Result::Ok,"resync receive");bool sameTest=false;for(const auto&f:received)if(f.header.type==MessageType::MachineStatus){MachineStatus s;sameTest=DecodeMachineStatus(f.payload,s)&&s.testId==77&&s.testRunning;}require(sameTest,"disconnect preserves test/reconnect status");close(re);server.Stop();
    std::cout<<"Protocol V1 mock client/offline integration tests passed\n";
}
